name: Run Playwright QA Test

on:
  push:
    branches:
      - main

jobs:
  run-playwright:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install playwright

      - name: Run QA Automation - 23f3001760@ds.study.iitm.ac.in
        run: node scrape_and_sum.js
